language: python

notifications:
  email: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libhdf5-serial-dev
    - pip uninstall numpy -y 
    - pip install numpy>=1.10.4
    - pip install requests
    - pip install pytz
    - pip install tornado
    - pip install watchdog
    - git clone https://github.com/HDFGroup/hdf5-json.git
    - cd hdf5-json
    - python setup.py install
    - cd .. 
    - git clone https://github.com/HDFGroup/h5serv.git


script:
    - cd h5serv/util/admin
    - python makepwd_file.py
    - python update_pwd.py -a -u test_user1 -p test
    - python update_pwd.py -a -u test_user2 -p test
    - cd ../..
    - python server/app.py >app.out &
    - sleep 5
    - cd ..
    - python setup.py install
    - python testall.py
