dist: xenial   # required for Python >= 3.7
language: python
notifications:
  email: false
python:
- '3.6'
- '3.7'
- '3.8'
env:
- H5_DRIVER=h5serv
- H5_DRIVER=hsds
install:
- sudo apt-get update -qq
- pip uninstall numpy -y
- pip install numpy>=1.17.3
- pip install requests
- pip install pytz
- pip install h5py
- if [ "${H5_DRIVER}" == "h5serv" ]; then
     pip install tornado ;
     pip install watchdog ;
     git clone https://github.com/HDFGroup/hdf5-json.git ;
     cd hdf5-json ;
     python setup.py install ;
     cd .. ;
     git clone https://github.com/HDFGroup/h5serv.git ;
  else
     pip install aiohttp ;
     pip install awscli ;
     git clone https://github.com/HDFGroup/hsds.git ;
     cd hsds ;
     ./build.sh --nolint ;
     ./runall.sh ;
     echo "server starting..."
     sleep 20 ;
     cd - ;
  fi
script:
- echo h5_driver ${H5_DRIVER}
- if [ "${H5_DRIVER}" == "h5serv" ]; then
    echo "setting up h5serv" ;
    cd h5serv/util/admin ;
    python makepwd_file.py ;
    python update_pwd.py -a -u test_user1 -p test ;
    python update_pwd.py -a -u test_user2 -p test ;
    cd ../.. ;
    python h5serv >app.out &
    sleep 5 ;
    cd .. ;
    export HS_ENDPOINT=http://127.0.0.1:5000 ;
    export H5PYD_TEST_FOLDER=h5pyd_test.hdfgroup.org ;
    export HS_PASSWORD=test ;
    export TEST2_PASSWORD=test ;
  elif [ "${H5_DRIVER}" == "hsds" ]; then
    export HS_ENDPOINT=http://localhost:5101 ;
    curl ${HS_ENDPOINT}/about ;
    export H5PYD_TEST_FOLDER=/home/test_user1/h5pyd_test/${TRAVIS_PYTHON_VERSION}/ ;
    export HS_USERNAME=test_user1
    export HS_PASSWORD=test ;
    export TEST2_PASSWORD=test ;
  else
    export USE_H5PY=1 ;
  fi
- python setup.py install
- echo endpoint ${HS_ENDPOINT}
- echo python_version ${TRAVIS_PYTHON_VERSION}
- echo test folder ${H5PYD_TEST_FOLDER}
- echo user ${HS_USERNAME}
- echo password ${HS_PASSWORD}
- echo test2_user ${TEST2_USERNAME}
- echo test2 password ${TEST2_PASSWORD}
- if [ "${H5_DRIVER}" == "hsds" ]; then
    echo "setting up HSDS folders" ;
    hstouch -u admin -p admin /home/ ;
    hstouch -u admin -p admin -o test_user1 /home/test_user1/ ;
    hstouch /home/test_user1/h5pyd_test/ ;
    hstouch ${H5PYD_TEST_FOLDER} ;
  fi
- python testall.py
