name: h5pyd tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - h5py
  - jupyter
  - matplotlib
  - nb_conda_kernels
  - pytz
  - requests
  - s3fs
  - pip:
      - h5pyd @ git+https://github.com/hdfgroup/h5pyd  # latest from master
